//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLoginLog
    {
        public string logGuid { get; set; }
        public string userGuid { get; set; }
        public Nullable<int> loginType { get; set; }
        public string loginIpAddress { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
        public string loginIpAddressName { get; set; }
        public string loginName { get; set; }
        public string loginResult { get; set; }
        public string loginDescription { get; set; }
    }
}
