//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ProjectManagement_DBEntities : DbContext
    {
        public ProjectManagement_DBEntities()
            : base("name=ProjectManagement_DBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.ValidateOnSaveEnabled = false;
            this.Configuration.AutoDetectChangesEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AccountLoginLog> AccountLoginLog { get; set; }
        public virtual DbSet<ClassLeader> ClassLeader { get; set; }
        public virtual DbSet<Crew> Crew { get; set; }
        public virtual DbSet<DefemseRoom> DefemseRoom { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<GroupLeader> GroupLeader { get; set; }
        public virtual DbSet<NoticeDefense> NoticeDefense { get; set; }
        public virtual DbSet<OperationRecord> OperationRecord { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectModule> ProjectModule { get; set; }
        public virtual DbSet<ProjectModuleExamine> ProjectModuleExamine { get; set; }
        public virtual DbSet<ProjectPlan> ProjectPlan { get; set; }
        public virtual DbSet<ProjectTeam> ProjectTeam { get; set; }
        public virtual DbSet<ProjectTest> ProjectTest { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleAuthorization> RoleAuthorization { get; set; }
        public virtual DbSet<SoftClass> SoftClass { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<SysModule> SysModule { get; set; }
        public virtual DbSet<SysModuleButton> SysModuleButton { get; set; }
        public virtual DbSet<SysModuleColumn> SysModuleColumn { get; set; }
        public virtual DbSet<SysModuleForm> SysModuleForm { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<SysItemDetails> SysItemDetails { get; set; }
        public virtual DbSet<SysItems> SysItems { get; set; }
    }
}
