//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string projectGuid { get; set; }
        public string teamGuid { get; set; }
        public string projectName { get; set; }
        public string projectDesc { get; set; }
        public string projectTarget { get; set; }
        public string proApproval { get; set; }
        public string proPlan { get; set; }
        public string proDemand { get; set; }
        public string proDesign { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUserGuid { get; set; }
        public Nullable<System.DateTime> lastUpdateTime { get; set; }
        public string lastUpdateUserGuid { get; set; }
        public Nullable<System.DateTime> delTime { get; set; }
        public string delUserGuid { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    
        public virtual ProjectTeam ProjectTeam { get; set; }
    }
}
