//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAuthorization
    {
        public string authGuid { get; set; }
        public Nullable<int> authModuleType { get; set; }
        public string authModuleGuid { get; set; }
        public string authRoleGuid { get; set; }
        public Nullable<int> sortCode { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUserGuid { get; set; }
    }
}
