//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;

    public partial class SysModuleButton
    {
        public string sysBtnGuid { get; set; }
        public string sysBtnName { get; set; }
        public string sysBtnIcon { get; set; }
        public string sysBtnEvent { get; set; }
        public string sysBtnUrlAddress { get; set; }
        public Nullable<int> sortCode { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUserGuid { get; set; }
        public Nullable<System.DateTime> lastUpdateTime { get; set; }
        public string lastUpdateUserGuid { get; set; }
        public Nullable<System.DateTime> delTime { get; set; }
        public string delUserGuid { get; set; }
        public string sysModuleGuid { get; set; }
        public string sysEnCode { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual SysModule SysModule { get; set; }
    }
}
