//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysModule()
        {
            this.SysModuleButton = new HashSet<SysModuleButton>();
            this.SysModuleColumn = new HashSet<SysModuleColumn>();
            this.SysModuleForm = new HashSet<SysModuleForm>();
        }
    
        public string sysModuleGuid { get; set; }
        public string parentGuid { get; set; }
        public Nullable<int> sysModuleLv { get; set; }
        public string sysModuleName { get; set; }
        public string sysModuleIcon { get; set; }
        public string sysModuleUri { get; set; }
        public string sysModuleTarget { get; set; }
        public Nullable<bool> isMuen { get; set; }
        public Nullable<int> sortCode { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUserGuid { get; set; }
        public Nullable<System.DateTime> lastUpdateTime { get; set; }
        public string lastUpdateUserGuid { get; set; }
        public Nullable<System.DateTime> delTime { get; set; }
        public string delUserGuid { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysModuleButton> SysModuleButton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysModuleColumn> SysModuleColumn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysModuleForm> SysModuleForm { get; set; }
    }
}
