//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ly.ProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string teacherGuid { get; set; }
        public string roleGuid { get; set; }
        public string jobNumber { get; set; }
        public string teacherPwd { get; set; }
        public Nullable<int> teacherType { get; set; }
        public string teacherName { get; set; }
        public string teacherNation { get; set; }
        public string teacherPlace { get; set; }
        public Nullable<bool> teacherSex { get; set; }
        public string teacherBirthday { get; set; }
        public string stuQQ { get; set; }
        public string stuWeChat { get; set; }
        public string stuPhone { get; set; }
        public Nullable<int> sortCode { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUserGuid { get; set; }
        public Nullable<System.DateTime> lastUpdateTime { get; set; }
        public string lastUpdateUserGuid { get; set; }
        public Nullable<System.DateTime> delTime { get; set; }
        public string delUserGuid { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
